name: miaid
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^1.1.1
  cupertino_icons: ^1.0.0
  get_utils: ^3.13.0
  country_code_picker: ^1.7.0
  pin_code_fields: ^6.0.1
  mask_text_input_formatter: ^1.2.1
  modal_bottom_sheet: ^1.0.0+1
  sliding_up_panel: ^1.0.2
  toggle_switch: ^0.1.8
  google_maps_flutter: ^1.0.10
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.2.2
  pedantic: ^1.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/NavBar/
    - assets/

flutter_native_splash:
  image: assets/splash/splash.png
  color: "ffffff"
  fill: true

flutter_intl:
  enabled: true
